

POST http://localhost:8000/getUserAssets HTTP/1.1
Content-Type: application/json
accessToken : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvb2xndXlzaXVuQG5hdmVyLmNvbSIsImlhdCI6MTY4NDUwNDA4MCwiZXhwIjoxNjg0NTA0NjgwfQ.8gdwgKcEbJMLR7nGFxhgSN_ri6mvVgcBzrMPa59gPgg
refreshToken : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODQ1MDExMDEsImV4cCI6MTY4NTcxMDcwMX0.YK1CzwQnX2o8m42Lyg44XzUtufi0CTrngBAc1fAESw4

{
    "email" : "coolguysiun@naver.com"
}

###

POST http://localhost:8000/getRefreshToken HTTP/1.1
Content-Type: application/json

{
    "email" : "coolguysiun@naver.com"
}

###
POST http://localhost:8000/getAccessToken HTTP/1.1
Content-Type: application/json

{
    "email" : "coolguysiun@naver.com"
}

###