GET http://localhost:8000/getAllStocks

###

POST http://localhost:8000/setRefreshToken
Content-Type: application.json

{
    "token" : "coolguysiun@Naver.com"
}

###

GET http://localhost:8000/getRefreshToken