# Generated by Django 4.1.7 on 2023-05-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USERASSET',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('amount', models.FloatField()),
                ('investmentperiod', models.IntegerField()),
            ],
            options={
                'db_table': 'USERASSET',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='USERTBL',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('age_range', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'USERTBL',
                'managed': False,
            },
        ),
    ]
