# Generated by Django 4.1.7 on 2023-03-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_tutorial_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTBL',
            fields=[
                ('k_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('k_name', models.CharField(max_length=20)),
                ('k_email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'UserTBL',
            },
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
