# Generated by Django 4.1.7 on 2023-03-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_usertbl_delete_tutorial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertbl',
            options={'managed': False},
        ),
    ]
