# Generated by Django 4.1.7 on 2023-03-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_usertbl_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStocks',
            fields=[
                ('email', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stock', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('amout', models.FloatField()),
            ],
            options={
                'db_table': 'UserTBL',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='usertbl',
            options={},
        ),
    ]
